# Generated by Django 4.1.3 on 2022-12-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Airline', models.CharField(choices=[('Emirates', 'Emirates Airline'), ('Airik', 'Airik Airline'), ('Peace', 'Peace Airline'), ('New Benin', 'New Benin Airline'), ('Danfo', 'Danfo Airline')], max_length=30)),
                ('Flying_From', models.CharField(choices=[('ABUJA', 'Abuja'), ('KANO', 'Kano'), ('LAGOS', 'Lagos'), ('ABIA', 'Abia')], max_length=50)),
                ('Flying_To', models.CharField(choices=[('ENUGU', 'Enugu'), ('EDO', 'Edo'), ('KOGI', 'Kogi'), ('KWARA', 'Kwara')], max_length=50)),
                ('Depature_date', models.DateField()),
                ('Adult', models.CharField(choices=[('One', '1'), ('Two', '2'), ('Three', '3'), ('Four', '4'), ('Five', '5'), ('Six', '6'), ('Seven', '7'), ('Eight', '8'), ('Nine', '9')], max_length=30)),
                ('Child', models.CharField(choices=[('One', '1'), ('Two', '2'), ('Three', '3'), ('Four', '4'), ('Five', '5'), ('Six', '6'), ('Seven', '7'), ('Eight', '8'), ('Nine', '9')], max_length=30)),
                ('Infant', models.CharField(choices=[('One', '1'), ('Two', '2'), ('Three', '3'), ('Four', '4'), ('Five', '5'), ('Six', '6'), ('Seven', '7'), ('Eight', '8'), ('Nine', '9')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('phone', models.PositiveIntegerField()),
                ('id_type', models.CharField(choices=[('NIN', 'NIN'), ('voters', "Voter's Card"), ('visa', 'Visa')], max_length=10)),
                ('passport', models.ImageField(upload_to='')),
            ],
        ),
    ]
